shellEmulator: true

trustPolicy: no-downgrade

packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalogs:
  cli:
    "@antfu/ni": ^28.2.0
    "@kirklin/eslint-config": ^7.0.0
    bumpp: ^10.4.0
    eslint: ^9.39.2
    eslint-plugin-format: ^1.3.1
    esno: ^4.8.0
    lint-staged: ^16.2.7
    pnpm: ^10.28.2
    rimraf: ^6.1.2
    simple-git-hooks: ^2.13.1
    taze: ^19.9.2
    typescript: ^5.9.3
    unbuild: ^3.6.1
    vite: ^7.3.1
  dev:
    "@kirklin/logger": ^0.1.1
  testing:
    vitest: ^4.0.18
  types:
    "@types/node": ^25.1.0
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
