packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalogs:
  cli:
    "@antfu/ni": ^25.0.0
    "@kirklin/eslint-config": ^5.0.0
    bumpp: ^10.2.2
    eslint: ^9.33.0
    eslint-plugin-format: ^1.0.1
    esno: ^4.8.0
    lint-staged: ^16.1.5
    pnpm: ^10.14.0
    rimraf: ^6.0.1
    simple-git-hooks: ^2.13.1
    taze: ^19.1.0
    typescript: ^5.9.2
    unbuild: ^3.6.0
    vite: ^7.1.1
  dev:
    "@kirklin/logger": ^0.1.1
  testing:
    vitest: ^3.2.4
  types:
    "@types/node": ^24.2.1
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
